title: JSONSpec
description: make the world well-typed.
theme: kimmy-site-theme
plugins:
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-optional-front-matter
destination: docs
