title: JSONSpec
description: make the world well-typed.
github:
  repository_url: https://github.com/kenpusney/spec
  repository_name: JSONSpec
  owner_url: https://github.com/kenpusney
  owner_name: Kimmy Leo
remote_theme: kenpusney/kimmy-site-theme
plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-optional-front-matter
